source 'https://rubygems.org'
source 'http://gemserver.iba.com.br/'

gem 'sinatra'
gem 'mongoid'
gem 'mongoid_migrations'
gem 'pry'
gem 'pry-nav'
gem 'cucumber'
gem 'rspec'
gem 'rack-test'
gem 'capybara'
